### ISSUE TITLE
patch to fix the old seg fault bug 

### ISSUE THREAD

**Issue by s-victor** [godfryd/noiz2sa#1]
Hello, glad to see someone is improving the code of this game.
It is known that this game suffers a segfault bug (which randomly happens when game was actively played for a few mins, and pretty much makes this game unplayable) on unix system, and I found a patch elsewhere which fix this bug.

To fix, replace the line 79 in "/src/foecommand.cc":
``foe->d = (int)(d*DIV/360);``
with:
``foe->d = (int)(d*DIV/360) & (DIV-1);``

The original patch was created by someone for rrootage (a game made by same author, which shares quite a lot same code), the following notes is extracted from the original patch if you are interested:

> rrootage has its own trig routines. Angles are represented as a number
between 0 and DIV (= 1024), where DIV = 2pi. sin and cos are
implemented as a simple table lookup, so it's important that all
angles stay within this range. In the doChangeDirection method (called
from libbulletml), this restriction wasn't obeyed.

You can find more info from "packages.debian.org/sid/rrootage", original patch is called "10_deg_out_of_range.patch" in "rrootage_0.23a-12.debian.tar.xz".

I have already filed the bug to its maintainer but wouldn't expect any change any time sooner.
Regards.

**Comment by godfryd** [comment]
Fixed in commit https://github.com/godfryd/noiz2sa/commit/bf1af9221a55c8ecd9102637090ff1521ff3d508
